# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      # Use actual Ansible Galaxy role name for the project directory.
      - run: cd ../
      - run: mv ansible-role-easyrsa vduseev.easyrsa
      - run: cd vduseev.easyrsa
      - run: pip install molecule docker
      - run: molecule test
